### PR TITLE
made eradicate 1.0 compatible

### PR DESCRIPTION
**Pull request by avallbona**
Made eradicate 1.0 compatible

Added the --aggressive option as False by default and the possibility to add it from console or configuration.

### CODE REVIEW

**Comment by aequitas** [comment]
Awesome, thx!

**Comment by avallbona** [comment]
Hi, would you consider to release the package to https://pypi.org/project/pytest-eradicate/ ?  
As the 0.0.4 version.
Thanks

**Comment by aequitas** [comment]
It should now be available at: https://pypi.org/manage/project/pytest-eradicate/release/0.0.4/

Sorry I forgot, this is one of my few projects I hadn't automated yet.

**Comment by avallbona** [comment]
Great!!
Thanks.

**Pull request merged**
